In [1]:
import torch

In [2]:
torch.set_default_device('cuda')

In [3]:
from generator import *
from discriminator import *

In [4]:
generator = Generator(8, [128, 256, 512], [], [], 9)
discriminator = RGCNLayer(len(BONDS), len(MOLS)+1, 3)

In [5]:
out=generator.generate(sample(28,8))
a=out['A']
x=out['X']

In [6]:
left,right=discriminator(x,a)

In [10]:
(left+right)

tensor([[[-4.9492e-01, -4.4210e-01,  8.4222e-02],
         [-1.3043e-01, -1.4997e-01, -2.5317e-01],
         [-5.9610e-02, -5.1799e-02, -1.9945e-02],
         [ 5.1210e-01,  3.2369e-02,  6.0206e-01],
         [ 1.1745e-01,  1.6131e-02, -1.8890e-02],
         [ 2.1730e-02,  4.6076e-01, -9.2969e-01],
         [ 4.4639e-01,  2.3007e-01, -1.7618e-01],
         [ 3.1947e-01,  2.6064e-02, -2.0068e-01],
         [-2.6147e-02, -1.1886e-01, -5.1159e-02]],

        [[-1.6125e-01, -9.7185e-02, -9.0591e-02],
         [-1.8683e-01, -4.7660e-03, -6.3403e-02],
         [ 4.7900e-02,  8.1735e-01, -2.5138e-01],
         [-2.1634e-01,  2.3510e-01, -5.5721e-01],
         [-1.0960e-01, -1.2440e-01, -1.9885e-01],
         [ 9.2858e-02, -6.3780e-01,  1.9807e-01],
         [-9.7165e-02, -1.0539e+00,  9.4968e-01],
         [ 1.4716e-01,  1.3076e-01, -6.1098e-01],
         [ 3.6926e-01,  1.8042e-01, -2.1945e-01]],

        [[-3.6812e-01,  3.9771e-01, -4.8864e-01],
         [ 1.2774e-01, -1.3103e-01, -3.1097e-0

In [49]:
(left_side_alt-left)

tensor([[[ 0.0000e+00,  2.9802e-08,  0.0000e+00],
         [ 0.0000e+00,  4.7684e-07,  0.0000e+00],
         [-1.4901e-08, -3.7253e-09,  0.0000e+00],
         [ 0.0000e+00,  1.4901e-08,  3.7253e-09],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  1.4901e-08,  0.0000e+00],
         [-4.6566e-09,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  4.4703e-08,  1.4901e-08]],

        [[ 1.4901e-08,  0.0000e+00,  0.0000e+00],
         [-2.9802e-08, -7.4506e-09,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  1.4901e-08],
         [-2.9802e-08, -3.7253e-09,  2.9802e-08],
         [-9.3132e-10,  1.4901e-08,  7.4506e-09],
         [ 0.0000e+00, -1.1176e-08,  0.0000e+00],
         [ 7.4506e-09, -1.4901e-08, -1.4901e-08],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  2.9802e-08,  0.0000e+00]],

        [[-3.7253e-09,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00, -7.4506e-09,  0.0000e+0

In [45]:
left

tensor([[[ 1.7348e-01, -7.7488e-02,  2.5969e-01],
         [ 3.3024e+00,  5.0485e+00,  3.7637e+00],
         [ 1.5122e-01,  5.2430e-02, -4.2111e-03],
         [-5.3643e-02, -1.2524e-01, -4.8842e-02],
         [-9.3974e-02,  1.3384e-01,  1.0897e-01],
         [-6.2372e-02, -1.4089e+00, -5.1641e-01],
         [-5.2252e-02, -1.1381e-01, -5.4481e-02],
         [-1.1279e-02,  1.7319e-01,  2.1025e-01],
         [ 1.9054e-01, -1.4775e-01, -1.5002e-01]],

        [[-2.5016e-02,  2.8319e-01,  5.6747e-02],
         [ 1.7051e-01, -5.4713e-02, -2.3416e-01],
         [-1.3833e-01, -2.2900e-01,  8.3959e-02],
         [-2.8272e-01, -4.9521e-02,  2.1347e-01],
         [-3.7782e-03,  1.7846e-01, -5.2702e-02],
         [ 5.5812e-01, -4.2945e-02, -4.3980e-01],
         [ 4.8985e-02, -4.1076e-02, -1.0569e-01],
         [-1.8810e-01,  2.3632e-02,  1.4611e-01],
         [-1.5264e-01, -3.8698e-02,  1.5094e-02]],

        [[ 2.0885e-02, -5.0310e-02, -8.9153e-04],
         [ 1.7205e-01,  6.2925e-02, -7.9384e-0

In [118]:
torch.stack(tmp1s).shape, tmp1_alt.shape

(torch.Size([3, 28, 9, 4]), torch.Size([28, 3, 9, 4]))

In [119]:
(torch.stack(tmp1s).permute(1,2,0,3)==tmp1_alt).all()

RuntimeError: The size of tensor a (3) must match the size of tensor b (9) at non-singleton dimension 2

In [27]:
tmp1=torch.einsum('abcd,xyz->ayz',a,x)
tmp2=torch.einsum(a,[0,...,1,2],x,[3,4,5],[0,4,5])

In [28]:
(tmp1==tmp2).all()

tensor(True, device='cuda:0')

In [23]:
tmp2[:2,:2,:2]

tensor([[[-1.7703, -0.8013],
         [-3.4854, -0.4069]],

        [[-0.9643, -0.4364],
         [-1.8984, -0.2216]]], device='cuda:0', grad_fn=<SliceBackward0>)

In [ ]:
torch.randn(123,456,789).permute(-1,0,1).shape

In [ ]:
(A*A==A).all()

In [ ]:
def gamma_k(k, phi1, theta1, var_e=1):
    if k==0:
        return (var_e) * (1-2*phi1*theta1+theta1**2) / (1-phi1**2)
    elif k==1:
        return phi1*gamma_k(0, phi1, theta1, var_e=var_e)-theta1*(var_e)
    else:
        return (phi1**k)*gamma_k(k-1, phi1, theta1, var_e=var_e)
def rho_k(k, phi1, theta1, var_e=1):
    return gamma_k(k, phi1, theta1, var_e=var_e)/gamma_k(0, phi1, theta1, var_e=var_e)

In [ ]:
phi1=0.4
theta1=0.5
var=4
print("gamma_0", '%.4f' % gamma_k(0,phi1,theta1,var), sep='\t')
print("rho_1", '%.4f' % rho_k(1,phi1,theta1,var), sep='\t')

In [ ]:
gamma_k(0,0.4,-0.5,4)

In [ ]:
rho_k(1,0.6,0.3)